/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lananda' at '3/7/17 8:02 PM' with Gradle 3.1
 *
 * @author lananda, @date 3/7/17 8:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
